// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJpsLTjdb46QtAnKhu300XGQWNoUAXXoA',
    appId: '1:784084758594:web:99ffde73fc080f149cbddb',
    messagingSenderId: '784084758594',
    projectId: 'weatherwardrobe-5c9f7',
    authDomain: 'weatherwardrobe-5c9f7.firebaseapp.com',
    storageBucket: 'weatherwardrobe-5c9f7.firebasestorage.app',
    measurementId: 'G-MCZXLDK9BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOMdHdSI-QHFElUbniSoMK-cRxqZIB5Tw',
    appId: '1:784084758594:android:26982f9ef96e49b39cbddb',
    messagingSenderId: '784084758594',
    projectId: 'weatherwardrobe-5c9f7',
    storageBucket: 'weatherwardrobe-5c9f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8PdmlqKxu7OSsVEA27IT55CRNpnxz78',
    appId: '1:784084758594:ios:d9e32b5088c940999cbddb',
    messagingSenderId: '784084758594',
    projectId: 'weatherwardrobe-5c9f7',
    storageBucket: 'weatherwardrobe-5c9f7.firebasestorage.app',
    iosBundleId: 'com.example.weatherWardrobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8PdmlqKxu7OSsVEA27IT55CRNpnxz78',
    appId: '1:784084758594:ios:d9e32b5088c940999cbddb',
    messagingSenderId: '784084758594',
    projectId: 'weatherwardrobe-5c9f7',
    storageBucket: 'weatherwardrobe-5c9f7.firebasestorage.app',
    iosBundleId: 'com.example.weatherWardrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJpsLTjdb46QtAnKhu300XGQWNoUAXXoA',
    appId: '1:784084758594:web:cf7e74f6fc011d0b9cbddb',
    messagingSenderId: '784084758594',
    projectId: 'weatherwardrobe-5c9f7',
    authDomain: 'weatherwardrobe-5c9f7.firebaseapp.com',
    storageBucket: 'weatherwardrobe-5c9f7.firebasestorage.app',
    measurementId: 'G-85K698BN61',
  );
}
